apiVersion: source.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: karmada
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: podinfo
      version: "1.6.1"
      sourceRef:
        kind: HelmRepository
        name: karmada
        namespace: default
      interval: 1m
