apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: karmada
  namespace: karmada-system
spec:
  interval: 5m
  chart:
    spec:
      chart: karmada
      version: "1.6.1"
      sourceRef:
        kind: GitRepository
        name: karmada
        namespace: karmada-system
      interval: 1m
  timeout: 10m
