---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kepler
  namespace: flux-system
spec:
  interval: 24h
  url: https://sustainable-computing-io.github.io/kepler-helm-chart
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kepler
  namespace: flux-system
spec:
  interval: 24h
  values:
    serviceMonitor:
      enabled: "true"
      namespace: "monitoring"
  targetNamespace: monitoring
  chart:
    spec:
      chart: kepler
      version: '0.5.3'
      sourceRef:
        kind: HelmRepository
        name: kepler
  dependsOn:
    - name: kube-prometheus-stack
