apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calico
  namespace: default
spec:
  chart:
    spec:
      chart: tigera-operator
      version: "3.26.1"
      sourceRef:
        kind: HelmRepository
        name: calico
        namespace: default
      interval: 1m
  install:
    createNamespace: true
  interval: 5m
  kubeConfig:
    secretRef:
      name: test-am-01-kubeconfig
  targetNamespace: tigera-operator
