apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: default
spec:
  chart:
    spec:
      chart: cilium
      version: "1.13.4"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: default
      interval: 1m
  interval: 5m
  kubeConfig:
    secretRef:
      name: test-am-01-kubeconfig
  targetNamespace: kube-system
  values:
    MTU: "1200"
    global:
      endpointRoutes:
        enabled: "true"
      ipam:
        mode: cluster-pool
        operator:
          clusterPoolIPv4PodCIDR: 192.168.0.0/16
          clusterPoolIPv4MaskSize: "23"
      nativeRoutingCIDR: 192.168.0.0/16 
    image:
      repository: quay.io/cilium/cilium
    kubeProxyReplacement: disabled    
