apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: default
spec:
  chart:
    spec:
      chart: grafana
      version: "6.58.4"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: default
      interval: 1m
  install:
    createNamespace: true
  interval: 5m
  kubeConfig:
    secretRef:
      name: test-am-01-kubeconfig
  targetNamespace: monitoring
