apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kepler
  namespace: default
spec:
  chart:
    spec:
      chart: kepler
      version: "0.4.4"
      sourceRef:
        kind: HelmRepository
        name: kepler
        namespace: default
      interval: 1m
  install:
    createNamespace: true
  interval: 5m
  kubeConfig:
    secretRef:
      name: test-am-01-kubeconfig
  targetNamespace: monitoring
