apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: default
spec:
  chart:
    spec:
      chart: prometheus
      version: "23.1.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: default
      interval: 1m
  install:
    createNamespace: true
  interval: 5m
  kubeConfig:
    secretRef:
      name: test-am-01-kubeconfig
  targetNamespace: monitoring
  timeout: 5m
  values:
    alertmanager:
      persistentVolume:
        enabled: "false"
    server:
      persistentVolume:
        enabled: "false"
