apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: karmada
  namespace: karmada-system
spec:
  interval: 5m0s
  url: https://raw.githubusercontent.com/karmada-io/karmada/master/charts
