apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kepler
  namespace: default
spec:
  interval: 5m0s
  url: https://sustainable-computing-io.github.io/kepler-helm-chart
