name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: green-reviews-runner-set
    steps:
    - run: echo "🎉 This job uses runner scale set runners!"
    - run: sleep 30
    - run: echo "🎉 done"
